### ISSUE TITLE
Error while loading entity prototype "Pony"

### ISSUE THREAD

**Issue by DonParpan** [suclearnub/my-little-factorio#1] opened 2018-01-04 15:19 UTC
**Version:** 0.1.1

**Issue:** Error on load

**Steps to reproduce:**
1. Add mod
2. start game

**Additional information:** No thanks

**Log:** https://pastebin.com/Jh4WFCUL

**Comment by the-emerald** [comment] 2018-01-04 15:43
Looks like the issue is with the fact that there's no sprite/animations that the "Pony" prototype can use. To-do in #2.

Will keep this issue open in case completing #2 does not solve the issue.

**Comment by the-emerald** [comment] 2018-01-04 23:34
I am investigating using existing character model (one with hardhat) to test functionality in the rest of the mod, as art asset creation, even if just a placeholder, can take quite a bit of time.

**Comment by the-emerald** [comment] 2018-01-05 01:51
Potential stopgap fix by using the existing character model done in f95364e - released as v0.1.2

Please check if it solves the issue.

**Comment by the-emerald** [comment] 2018-01-05 15:57
Fixed in f95364e.

**Closed as completed by the-emerald** 2018-01-05 15:57 UTC
Labels: bug
